[target.aarch64-linux-android]
linker = "/home/debian/Android/Sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-aarch64/bin/aarch64-linux-android24-clang"
ar = "/home/debian/Android/Sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/linux-aarch64/bin/llvm-ar"
