name: berry_rss
description: "BerryRSS Reader Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  xml: ^7.0.1
  shared_preferences: ^2.5.5
  webview_flutter: ^4.14.1
  share_plus: ^13.3.0
  image_picker: ^1.2.3
  flutter_rust_bridge: 2.13.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.2
  local_auth: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: any
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
