// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TsumiItemData`

Future<bool> checkIsRotten({
  required PlatformInt64 createdAtEpoch,
  required PlatformInt64 currentEpoch,
}) => RustLib.instance.api.crateApiSimpleCheckIsRotten(
  createdAtEpoch: createdAtEpoch,
  currentEpoch: currentEpoch,
);

Future<int> calculateConsumeReward({
  required bool isRotten,
  required bool isRare,
}) => RustLib.instance.api.crateApiSimpleCalculateConsumeReward(
  isRotten: isRotten,
  isRare: isRare,
);

Future<bool> determineIfRare({required int randomSeed}) =>
    RustLib.instance.api.crateApiSimpleDetermineIfRare(randomSeed: randomSeed);
