name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'master'
          channel: 'master'
          cache: true

      - name: Add iOS targets for Rust
        run: |
          rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App for Simulator
        run: flutter build ios --debug --simulator --no-codesign

      - name: Create IPA package
        run: |
          mkdir Payload
          cp -r build/ios/iphonesimulator/Runner.app Payload/
          zip -r TumiYomi-Simulator.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TumiYomi-IPA
          path: TumiYomi-Simulator.ipa
